In [104]:
import numpy as np
import utils

In [91]:
def split_square(square):
    #first split vertically, then split horizontally. Returns a 2-d list
    size = len(square)
    if size == 2 or size == 3:
        return [[square]]
    num_subsquare = size / 2 if len(square) % 2 == 0 else size / 3
    return [np.split(half, num_subsquare, 1) for half in np.split(square, num_subsquare, 0)]

In [25]:
def rotate(array, times=1):
    for i in range(times):
        array = np.rot90(array)
    return array

In [117]:
def permutations(square):
    return [rotate(square, times=i) for i in range(4)] + [rotate(np.fliplr(square), times=i) for i in range(4)]

In [74]:
def str_to_array(s):
    conv = {'.': 0, '#': 1}
    return np.array([list(map(lambda x: conv[x], r)) for r in s.split('/')])

In [75]:
def array_to_str(arr):
    conv = {0: '.', 1: '#'}
    return '/'.join([''.join(list(map(lambda x: conv[x], r))) for r in arr])

In [111]:
rules = {"../.#": np.array([[1, 1, 0], [1, 0, 0], [0, 0, 0]]),
         ".#./..#/###": np.array([[1, 0, 0, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 0, 0, 1]])}

In [115]:
def find_enhancement(square):
    for perm in permutations(square):
        string_rep = array_to_str(perm)
        if string_rep in rules:
            return rules[string_rep]
    print("NOT FOUND")

In [122]:
def run(start_pattern, iterations):
    square = start_pattern
    for i in range(iterations):
        sub_squares = split_square(square)
        enhanced_squares = []
        for row in sub_squares:
            enhanced_squares.append(list(map(lambda x: find_enhancement(x), row)))
        square = np.vstack([np.hstack(row) for row in enhanced_squares])
        print(i)
    return np.sum(square)

In [112]:
start_pattern = np.array([[0, 1, 0], [0, 0, 1], [1, 1, 1]])
run(start_pattern, 2)

[[1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]]
[[1 1 0 1 1 0]
 [1 0 0 1 0 0]
 [0 0 0 0 0 0]
 [1 1 0 1 1 0]
 [1 0 0 1 0 0]
 [0 0 0 0 0 0]]


12

In [123]:
rules_data = utils.import_file("Inputs/input21.txt", split=True)
rules = {k: str_to_array(v) for k, v in [rule.split(" => ") for rule in rules_data]}
start_pattern = np.array([[0, 1, 0], [0, 0, 1], [1, 1, 1]])
#rules
run(start_pattern, 18)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


1782917